- name: Install LXD
  hosts: lxd_host_machines
  gather_facts: false
  roles:
    - role: zfs_pool
      zfs_pool_name: lxd-default
      zfs_pool_disks: "{{ config_lxd_zfs_pool_disks }}"

    - role: lxd_install
